<a href="https://colab.research.google.com/github/harshu4387/train/blob/main/train_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving train.csv to train.csv

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('train.csv')

In [ ]:
df.columns=df.columns.str.lower()

In [ ]:
df.shape

(19237, 18)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19237 entries, 0 to 19236
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                19237 non-null  int64
 1   price             19237 non-null  int64
 2   levy              19237 non-null  object
 3   manufacturer      19237 non-null  object
 4   model             19237 non-null  object
 5   prod. year        19237 non-null  int64
 6   category          19237 non-null  object
 7   leather interior  19237 non-null  object
 8   fuel type         19237 non-null  object
 9   engine volume     19237 non-null  object
 10  mileage           19237 non-null  object
 11  cylinders         19237 non-null  float64
 12  gear box type     19237 non-null  object
 13  drive wheels      19237 non-null  object
 14  doors             19237 non-null  object
 15  wheel             19237 non-null  object
 16  color             19237 non-null  object
 17  airbags           19237 non-null  int64
dtypes: float64(1), int64(4), object(13)
memory usage: 2.6+ MB

In [ ]:
df.size

346266

In [ ]:
df.dtypes

id                    int64
price                 int64
levy                 object
manufacturer         object
model                object
prod. year            int64
category             object
leather interior     object
fuel type            object
engine volume        object
mileage              object
cylinders           float64
gear box type        object
drive wheels         object
doors                object
wheel                object
color                object
airbags               int64
dtype: object

In [ ]:
df.describe()

                 id         price    prod. year     cylinders       airbags
count  1.923700e+04  1.923700e+04  19237.000000  19237.000000  19237.000000
mean   4.557654e+07  1.855593e+04   2010.912824      4.582991      6.582627
std    9.365914e+05  1.905813e+05      5.668673      1.199933      4.320168
min    2.074688e+07  1.000000e+00   1939.000000      1.000000      0.000000
25%    4.569837e+07  5.331000e+03   2009.000000      4.000000      4.000000
50%    4.577231e+07  1.317200e+04   2012.000000      4.000000      6.000000
75%    4.580204e+07  2.207500e+04   2015.000000      4.000000     12.000000
max    4.581665e+07  2.630750e+07   2020.000000     16.000000     16.000000

In [ ]:
df.isnull().sum()

id                  0
price               0
levy                0
manufacturer        0
model               0
prod. year          0
category            0
leather interior    0
fuel type           0
engine volume       0
mileage             0
cylinders           0
gear box type       0
drive wheels        0
doors               0
wheel               0
color               0
airbags             0
dtype: int64

In [ ]:
df.mean(numeric_only=True)

id            4.557654e+07
price         1.855593e+04
prod. year    2.010913e+03
cylinders     4.582991e+00
airbags       6.582627e+00
dtype: float64

In [ ]:
df.mean(numeric_only=True)

id            4.557654e+07
price         1.855593e+04
prod. year    2.010913e+03
cylinders     4.582991e+00
airbags       6.582627e+00
dtype: float64

In [ ]:
df.count()

id                  19237
price               19237
levy                19237
manufacturer        19237
model               19237
prod. year          19237
category            19237
leather interior    19237
fuel type           19237
engine volume       19237
mileage             19237
cylinders           19237
gear box type       19237
drive wheels        19237
doors               19237
wheel               19237
color               19237
airbags             19237
dtype: int64

In [ ]:
# car - red, yellow, orange 26k 40k 50k

# car. red yellow orange   cost
# car.  1.    0.    0.      26k
# car.  0.    1.    0.      40k
# car.  0.    0.    1.      50k

In [ ]:
# more appoved or rejected?
# bar chart of loan status
# box polt for loan amount
# which group has higher loan approval
# which feature looks important for loan approval